# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReplicatedLog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReplicatedLog.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13ReplicatedLog.proto\"\x1e\n\x04POST\x12\t\n\x01w\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1b\n\x0cPOSTResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x12\n\x03GET\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1b\n\x0bGETResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t29\n\x12PostRequestService\x12#\n\x0bPostRequest\x12\x05.POST\x1a\r.POSTResponse25\n\x11GetRequestService\x12 \n\nGetRequest\x12\x04.GET\x1a\x0c.GETResponseb\x06proto3'
)




_POST = _descriptor.Descriptor(
  name='POST',
  full_name='POST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='POST.w', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='POST.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=53,
)


_POSTRESPONSE = _descriptor.Descriptor(
  name='POSTResponse',
  full_name='POSTResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='POSTResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=82,
)


_GET = _descriptor.Descriptor(
  name='GET',
  full_name='GET',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='GET.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=102,
)


_GETRESPONSE = _descriptor.Descriptor(
  name='GETResponse',
  full_name='GETResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='GETResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=131,
)

DESCRIPTOR.message_types_by_name['POST'] = _POST
DESCRIPTOR.message_types_by_name['POSTResponse'] = _POSTRESPONSE
DESCRIPTOR.message_types_by_name['GET'] = _GET
DESCRIPTOR.message_types_by_name['GETResponse'] = _GETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

POST = _reflection.GeneratedProtocolMessageType('POST', (_message.Message,), {
  'DESCRIPTOR' : _POST,
  '__module__' : 'ReplicatedLog_pb2'
  # @@protoc_insertion_point(class_scope:POST)
  })
_sym_db.RegisterMessage(POST)

POSTResponse = _reflection.GeneratedProtocolMessageType('POSTResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSTRESPONSE,
  '__module__' : 'ReplicatedLog_pb2'
  # @@protoc_insertion_point(class_scope:POSTResponse)
  })
_sym_db.RegisterMessage(POSTResponse)

GET = _reflection.GeneratedProtocolMessageType('GET', (_message.Message,), {
  'DESCRIPTOR' : _GET,
  '__module__' : 'ReplicatedLog_pb2'
  # @@protoc_insertion_point(class_scope:GET)
  })
_sym_db.RegisterMessage(GET)

GETResponse = _reflection.GeneratedProtocolMessageType('GETResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESPONSE,
  '__module__' : 'ReplicatedLog_pb2'
  # @@protoc_insertion_point(class_scope:GETResponse)
  })
_sym_db.RegisterMessage(GETResponse)



_POSTREQUESTSERVICE = _descriptor.ServiceDescriptor(
  name='PostRequestService',
  full_name='PostRequestService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=133,
  serialized_end=190,
  methods=[
  _descriptor.MethodDescriptor(
    name='PostRequest',
    full_name='PostRequestService.PostRequest',
    index=0,
    containing_service=None,
    input_type=_POST,
    output_type=_POSTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSTREQUESTSERVICE)

DESCRIPTOR.services_by_name['PostRequestService'] = _POSTREQUESTSERVICE


_GETREQUESTSERVICE = _descriptor.ServiceDescriptor(
  name='GetRequestService',
  full_name='GetRequestService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=192,
  serialized_end=245,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRequest',
    full_name='GetRequestService.GetRequest',
    index=0,
    containing_service=None,
    input_type=_GET,
    output_type=_GETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETREQUESTSERVICE)

DESCRIPTOR.services_by_name['GetRequestService'] = _GETREQUESTSERVICE

# @@protoc_insertion_point(module_scope)
